# This file will be imported by spaND's main makefile.
#
# It needs to define build variables with **system-specific**
# information about dependencies.
#
# We have some templates for this file in tests/Makefile-confs/.
#
