
CC = clang++ -Wextra  -Wfatal-errors  -Wnull-dereference -Wno-sign-compare -Wno-int-in-bool-context # Needs gcc/8.* otherwise complex fails, somewhere

GTESTDIR = /Users/rjmurr/Documents/randnla/spand-deps/install/include
GTESTLIB = /Users/rjmurr/Documents/randnla/spand-deps/install/lib

MFEMDIR = /Users/rjmurr/Documents/randnla/spand-deps/install/include
MFEMLIB = /Users/rjmurr/Documents/randnla/spand-deps/install/lib

LAPACKPP_INCDIR = -I/Users/rjmurr/Documents/randnla/lapackpp-install/include
BLASPP_INCDIR = -I/Users/rjmurr/Documents/randnla/blaspp-install/include
LAPP_INCDIR = $(LAPACKPP_INCDIR) $(BLASPP_INCDIR)
EIGEN_DIR = -I/Users/rjmurr/Documents/randnla/spand-deps/install/include/Eigen
EXTRA_INCDIR = -I/Users/rjmurr/Documents/randnla/spand-deps/install/include $(LAPP_INCDIR) $(EIGEN_DIR)

LAPACKPP_LINKDIR = -L/Users/rjmurr/Documents/randnla/lapackpp-install/lib/
BLASPP_LINKDIR = -L/Users/rjmurr/Documents/randnla/blaspp-install/lib/
LAPP_LINKDIR = $(LAPACKPP_LINKDIR) $(BLASPP_LINKDIR)
EXTRA_LINKDIR = -L/Users/rjmurr/Documents/randnla/spand-deps/install/lib $(LAPP_LINKDIR)
