
CC = clang++  -Wfatal-errors -Wnull-dereference -Wno-sign-compare -Wno-format -Wno-int-in-bool-context

GTESTDIR = /Users/rjmurr/Documents/randnla/spand-deps/install/include
GTESTLIB = /Users/rjmurr/Documents/randnla/spand-deps/install/lib

MFEMDIR = /Users/rjmurr/Documents/randnla/spand-deps/install/include
MFEMLIB = /Users/rjmurr/Documents/randnla/spand-deps/install/lib

# use -isystem instead of -I for includes where we don't want to hear about certain compiler warnings.
LAPACKPP_INCDIR = -isystem/Users/rjmurr/Documents/randnla/lapackpp-install/include
BLASPP_INCDIR = -isystem/Users/rjmurr/Documents/randnla/blaspp-install/include
LAPP_INCDIR = $(LAPACKPP_INCDIR) $(BLASPP_INCDIR)
EIGEN_DIR = -I/Users/rjmurr/Documents/randnla/spand-deps/install/include/Eigen
EXTRA_INCDIR = -I/Users/rjmurr/Documents/randnla/spand-deps/install/include $(LAPP_INCDIR) $(EIGEN_DIR)

LAPACKPP_LINKDIR = -L/Users/rjmurr/Documents/randnla/lapackpp-install/lib/
BLASPP_LINKDIR = -L/Users/rjmurr/Documents/randnla/blaspp-install/lib/
LAPP_LINKDIR = $(LAPACKPP_LINKDIR) $(BLASPP_LINKDIR)
EXTRA_LINKDIR = -L/Users/rjmurr/Documents/randnla/spand-deps/install/lib $(LAPP_LINKDIR)
